---
# This workflow is designed to clean up old Docker container versions in a GitHub repository.
name: Cleanup SNAPSHOT Versions
run-name: "${{ github.event_name }} - ${{ github.actor }}"
on:
  workflow_dispatch:
    inputs:
      threshold-days:
        description: "Number of days to keep container versions"
        required: false
        default: "0"
      threshold-versions:
        description: "Number of versions to keep"
        required: false
        default: "5"
      dry-run:
        description: "Enable dry-run mode"
        required: false
        default: "true"
permissions:
  contents: read
  packages: write

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: "Summary"
        run: |
          echo "**Event**: ${{ github.event_name }}"
          echo "**Actor**: ${{ github.actor }}"
          echo "**Threshold days**: ${{ github.event.inputs.threshold-days || 8 }}"
          echo "**Included tags**: ${{ github.event.inputs.included-tags || 'dev*' }}"
          echo "**Excluded tags**: ${{ github.event.inputs.excluded-tags || 'release*' }}"
          echo "**Dry-run**: ${{ github.event.inputs.dry-run || 'false' }}"

      - name: Run Container Package Cleanup Action
        uses: netcracker/qubership-workflow-hub/actions/container-package-cleanup@feature/cleanup-packages
        with:
          threshold-days: ${{ github.event.inputs.threshold-days || 8 }}
          package-type: maven
          threshold-versions: ${{ github.event.inputs.threshold-versions || 1 }}
          dry-run: ${{ github.event.inputs.dry-run || 'false' }}
        env:
          PACKAGE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
