name: Maven & NPM Release

run-name: Maven & NPM Release ${{ inputs.release-version || 'auto' }}

on:
  workflow_dispatch:
    inputs:
      # =================================
      # GENERAL SETTINGS
      # =================================
      release-version:
        description: 'Release version for both Maven and NPM (e.g., 1.0.0)'
        required: false
        type: string
      maven-release:
        description: 'Run Maven release'
        required: false
        type: boolean
        default: true
      npm-publish:
        description: 'Run NPM publish'
        required: false
        type: boolean
        default: true
      # =================================
      # MAVEN CONFIGURATION
      # =================================
      maven-profile:
        description: 'Maven profile to use'
        type: choice
        options:
          - 'github'
          - 'central'
        required: false
        default: 'central'
      maven-java-version:
        description: 'Java version (e.g., 21)'
        required: false
        type: string
        default: '21'
      maven-build-docker:
        description: 'Build Docker image for Maven project'
        required: false
        type: boolean
        default: false
      maven-dry-run:
        description: 'Maven dry run'
        required: false
        type: boolean
        default: false
      # =================================
      # NPM CONFIGURATION
      # =================================
      npm-scope:
        description: 'NPM scope for the package'
        required: false
        type: string
        default: '@netcracker'
      npm-dist-tag:
        description: 'NPM distribution tag'
        required: false
        type: string
        default: 'latest'

permissions:
  contents: write
  packages: write

jobs:
  maven-release:
    if: ${{ inputs.maven-release && inputs.maven-release != 'false' }}
    uses: ./.github/workflows/maven-release.yaml
    with:
      version: ${{ inputs.release-version }}
      profile: ${{ inputs.maven-profile }}
      java-version: ${{ inputs.maven-java-version }}
      build-docker: ${{ inputs.maven-build-docker }}
      dry-run: ${{ inputs.maven-dry-run }}
    secrets: inherit

  npm-publish:
    if: ${{ inputs.npm-publish && inputs.npm-publish != 'false' }}
    uses: Netcracker/qubership-workflow-hub/.github/workflows/re-npm-publish.yml@main
    with:
      version: ${{ inputs.release-version }}
      scope: ${{ inputs.npm-scope }}
      dist-tag: ${{ inputs.npm-dist-tag }}
      ref: ${{ github.ref_name }}
    secrets: inherit
